spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test-shop-auth;Mode=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  flyway:
    locations: classpath:/db/test
jwt:
  secret: yhujgugy*&Uhiukjhnd78*&h887d087cd8799*!&@#!#%HNiolk656G&G&^^%67tgiujh0(*Ho8yf56E$E&%^D4532WS#@S%76rf76r5%6fr5r
  lifetime: 3600000 # время в миллисекундах