server:
  port: 8081
  servlet:
    context-path: /shop-carts

integrations:
  product-service:
    url: http://localhost:8082/shop
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000