server:
  port: 8081
  servlet:
    context-path: /shop-carts
jwt:
  secret: yhujgugy*&Uhiukjhnd78*&h887d087cd8799*!&@#!#%HNiolk656G&G&^^%67tgiujh0(*Ho8yf56E$E&%^D4532WS#@S%76rf76r5%6fr5r
rest-template:
  products: http://localhost:8082/shop/api/v1/products