server:
  port: 8081
  servlet:
    context-path: /shop-carts

spring:
  redis:
    host: 192.168.0.4
    port: 6379

integrations:
  product-service:
    url: http://localhost:8082/shop
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000