//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.09 at 04:17:17 PM MSK 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://msvdev.org/ee/shop/ws/products", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.msvdev.ee.shop.soap.product;
